"""Country code & flag meta for the 48 teams. Uses flagcdn.com (ISO 3166-1 alpha-2)."""

def _flag(code: str) -> str:
    return f"https://flagcdn.com/w320/{code.lower()}.png"


TEAM_META = {
    "Algeria": {"code": "DZ", "flag": _flag("DZ"), "rank": 36, "coach": "Vladimir Petković"},
    "Argentina": {"code": "AR", "flag": _flag("AR"), "rank": 1, "coach": "Lionel Scaloni"},
    "Australia": {"code": "AU", "flag": _flag("AU"), "rank": 25, "coach": "Tony Popovic"},
    "Austria": {"code": "AT", "flag": _flag("AT"), "rank": 22, "coach": "Ralf Rangnick"},
    "Belgium": {"code": "BE", "flag": _flag("BE"), "rank": 8, "coach": "Domenico Tedesco"},
    "Bosnia and Herzegovina": {"code": "BA", "flag": _flag("BA"), "rank": 75, "coach": "Sergej Barbarez"},
    "Brazil": {"code": "BR", "flag": _flag("BR"), "rank": 5, "coach": "Carlo Ancelotti"},
    "Cabo Verde": {"code": "CV", "flag": _flag("CV"), "rank": 70, "coach": "Bubista"},
    "Canada": {"code": "CA", "flag": _flag("CA"), "rank": 30, "coach": "Jesse Marsch"},
    "Colombia": {"code": "CO", "flag": _flag("CO"), "rank": 14, "coach": "Néstor Lorenzo"},
    "Cote D'Voire": {"code": "CI", "flag": _flag("CI"), "rank": 41, "coach": "Emerse Faé"},
    "Croatia": {"code": "HR", "flag": _flag("HR"), "rank": 9, "coach": "Zlatko Dalić"},
    "Curacao": {"code": "CW", "flag": _flag("CW"), "rank": 82, "coach": "Dick Advocaat"},
    "Czechia": {"code": "CZ", "flag": _flag("CZ"), "rank": 42, "coach": "Ivan Hašek"},
    "DR Congo": {"code": "CD", "flag": _flag("CD"), "rank": 56, "coach": "Sébastien Desabre"},
    "Ecuador": {"code": "EC", "flag": _flag("EC"), "rank": 23, "coach": "Sebastián Beccacece"},
    "Egypt": {"code": "EG", "flag": _flag("EG"), "rank": 32, "coach": "Hossam Hassan"},
    "England": {"code": "GB-ENG", "flag": "https://flagcdn.com/w320/gb-eng.png", "rank": 4, "coach": "Thomas Tuchel"},
    "France": {"code": "FR", "flag": _flag("FR"), "rank": 2, "coach": "Didier Deschamps"},
    "Germany": {"code": "DE", "flag": _flag("DE"), "rank": 10, "coach": "Julian Nagelsmann"},
    "Ghana": {"code": "GH", "flag": _flag("GH"), "rank": 73, "coach": "Otto Addo"},
    "Haiti": {"code": "HT", "flag": _flag("HT"), "rank": 83, "coach": "Sébastien Migné"},
    "Iran": {"code": "IR", "flag": _flag("IR"), "rank": 18, "coach": "Amir Ghalenoei"},
    "Iraq": {"code": "IQ", "flag": _flag("IQ"), "rank": 58, "coach": "Graham Arnold"},
    "Japan": {"code": "JP", "flag": _flag("JP"), "rank": 15, "coach": "Hajime Moriyasu"},
    "Jordan": {"code": "JO", "flag": _flag("JO"), "rank": 64, "coach": "Jamal Sellami"},
    "Korea Republic": {"code": "KR", "flag": _flag("KR"), "rank": 23, "coach": "Hong Myung-bo"},
    "Mexico": {"code": "MX", "flag": _flag("MX"), "rank": 17, "coach": "Javier Aguirre"},
    "Morocco": {"code": "MA", "flag": _flag("MA"), "rank": 13, "coach": "Walid Regragui"},
    "Netherlands": {"code": "NL", "flag": _flag("NL"), "rank": 7, "coach": "Ronald Koeman"},
    "New Zealand": {"code": "NZ", "flag": _flag("NZ"), "rank": 86, "coach": "Darren Bazeley"},
    "Norway": {"code": "NO", "flag": _flag("NO"), "rank": 33, "coach": "Ståle Solbakken"},
    "Panama": {"code": "PA", "flag": _flag("PA"), "rank": 41, "coach": "Thomas Christiansen"},
    "Paraguay": {"code": "PY", "flag": _flag("PY"), "rank": 51, "coach": "Gustavo Alfaro"},
    "Portugal": {"code": "PT", "flag": _flag("PT"), "rank": 6, "coach": "Roberto Martínez"},
    "Qatar": {"code": "QA", "flag": _flag("QA"), "rank": 53, "coach": "Bartolomé Márquez"},
    "Saudi Arabia": {"code": "SA", "flag": _flag("SA"), "rank": 56, "coach": "Hervé Renard"},
    "Scotland": {"code": "GB-SCT", "flag": "https://flagcdn.com/w320/gb-sct.png", "rank": 39, "coach": "Steve Clarke"},
    "Senegal": {"code": "SN", "flag": _flag("SN"), "rank": 19, "coach": "Pape Thiaw"},
    "South Africa": {"code": "ZA", "flag": _flag("ZA"), "rank": 58, "coach": "Hugo Broos"},
    "Spain": {"code": "ES", "flag": _flag("ES"), "rank": 3, "coach": "Luis de la Fuente"},
    "Sweden": {"code": "SE", "flag": _flag("SE"), "rank": 41, "coach": "Jon Dahl Tomasson"},
    "Switzerland": {"code": "CH", "flag": _flag("CH"), "rank": 20, "coach": "Murat Yakin"},
    "Tunisia": {"code": "TN", "flag": _flag("TN"), "rank": 49, "coach": "Sami Trabelsi"},
    "Türkiye": {"code": "TR", "flag": _flag("TR"), "rank": 27, "coach": "Vincenzo Montella"},
    "USA": {"code": "US", "flag": _flag("US"), "rank": 16, "coach": "Mauricio Pochettino"},
    "Uruguay": {"code": "UY", "flag": _flag("UY"), "rank": 11, "coach": "Marcelo Bielsa"},
    "Uzbekistan": {"code": "UZ", "flag": _flag("UZ"), "rank": 57, "coach": "Timur Kapadze"},
}
